close all;
clear all;

cd(fileparts(mfilename('fullpath')));
addpath('./Classes')

setenv('CHOMP_ROOT_FOLDER', '');

opt = chomp_options(...
    'root_folder', getenv('CHOMP_ROOT_FOLDER'), ...
    'input_folder', '/neurotank/derived/gbohner/input/', ...
    'output_folder', '/neurotank/derived/gbohner/output/', ...
    'precomputed_folder', '/neurotank/derived/gbohner/precomputed/', ...
    'results_folder', '/neurotank/derived/gbohner/results', ...
    'data_type', 'frames_virtual', ...
    'NSS', 1, ...
    'init_model',{'filled'}, ...
    'stabilize',1, ...
    'niter', 4, ...
    'm', 17, ...
    'mom', 2, ...
    'fig',2, ...
    'spatial_scale',1,...
    'time_scale',1,...
    'mask', 0, ...
    'smooth_filter_mean',2, ...
    'smooth_filter_var',2, ...
    'cells_per_image', 30, ...
    'KS', 4 ...
  );


%For this one no tif images yet, in progress
%opt.data_path = '/neurotank/Watkins/2016-02-12/2P/CenterOutReach/site005/Tseries_20160212_Watkins_CenterOutReach_time20160212.123454.112-021/Tseries_20160212_Watkins_CenterOutReach_time20160212.123454.112-021_Cycle00001_Ch2_000001.ome.tif';
 
% % For local run and local data 
opt.data_path = '~/stanford/Tseries_20160219_Watkins_CenterOutReach_time20160219.133302.428-001/Tseries_20160219_Watkins_CenterOutReach_time20160219.133302.428-001_Cycle00001_Ch2_000001.ome.tif';
opt.input_folder = '~/stanford/input/';
opt.output_folder = '~/stanford/output/';
opt.precomputed_folder = '~/stanford/precomputed/';
opt.results_folder = '~/stanford/results/';

% Varius param settings
opt.spatial_scale = 1;
opt.m = 17;
opt.mom = 2;
opt.data_type = 'frames_virtual';
opt.init_model = {'filled', 'pointlike'}; % 'filled', 'donut', 'pointlike', \\ %TODO: 'supervised', 'multi'
opt.NSS = 2;
opt.KS = 4;
opt.cells_per_image = 25;
 

[~, opt.file_prefix] = fileparts(opt.data_path); % Important to have nice file prefixes (corresponding to folder name)

[opt, ROI_mask, ROIs] = chomp(opt);

get_cell_timeseries(opt);

% load('../data_for_gergo/S1-T52844_masks.mat', 'donut')

% figure(2); imshowpair(ROI_mask, donut>0);